### ISSUE TITLE
Dynamically configure the Redis Channel Name from Attribute

### ISSUE THREAD

**Issue by sriharibv** [Azure/azure-functions-redis-extension#106]
User should be able to configure the Redis channel name from the configuration file like Connection string.

**Comment by royland123** [comment]
The channel name can be resolved from the configuration by enclosing the value with percent signs such as "%pubsubChannel%". An example of this can be found [here](https://github.com/Azure/azure-functions-redis-extension/blob/main/samples/dotnet/RedisSamples.cs#L36C1-L36C13) on line 20.

**Comment by sriharibv** [comment]
Thanks a lot
