### ISSUE TITLE
Add support for AAD identity connections

### ISSUE THREAD

**Issue by tj-spyro** [Azure/azure-functions-redis-extension#113]
Azure Cache for Redis has [introduced support for AAD for authentication ](https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-azure-active-directory-for-authentication) and would be great if this was supported by the extension. 

This should have a similar [configuration experience](https://learn.microsoft.com/en-gb/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=python-v2%2Cin-process%2Cextensionv5&pivots=programming-language-csharp#identity-based-connections) to the [Service Bus extension](https://github.com/Azure/azure-sdk-for-net/tree/Microsoft.Azure.WebJobs.Extensions.ServiceBus_5.12.0/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus). For example:
```
<CONNECTION_NAME_PREFIX>__fullyQualifiedCacheHostName=<CACHE_HOST_NAME>.redis.cache.windows.net
``` 

The company I work for are in a position to move one of our services to functions now that there is Redis trigger support but we would much prefer to be using the function's managed identity instead of continuing to handle sensitive connection strings.

**Comment by mapalan** [comment]
Thanks for creating the issue. This is on our radar and we do plan on adding support for AAD authentication for connections.
