### ISSUE TITLE
Redis stream trigger System.ObjectDisposedException when scaling down

### ISSUE THREAD

**Issue by slwalker62** [Azure/azure-functions-redis-extension#154]
While using Runtime Scale Monitoring for a redis stream trigger, "System.ObjectDisposedException at StackExchange.Redis.ConnectionMultiplexer.ExecuteAsyncImpl" are appearing within application insights when what appears to be the consumers are scaling back down. It seems that it is attempting to query scaler metrics after the fact that the IConnectionMultiplexer being used was disposed. I have included the parsedStack from app insights.
This is an in-process function app running on .net 6.0.

[{"assembly":"StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46","method":"StackExchange.Redis.ConnectionMultiplexer.ExecuteAsyncImpl","level":0,"line":2176,"fileName":"/_/src/StackExchange.Redis/ConnectionMultiplexer.cs"},{"assembly":"StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46","method":"StackExchange.Redis.RedisBase.ExecuteAsync","level":1,"line":54,"fileName":"/_/src/StackExchange.Redis/RedisBase.cs"},{"assembly":"Microsoft.Azure.WebJobs.Extensions.Redis, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null","method":"Microsoft.Azure.WebJobs.Extensions.Redis.RedisStreamTriggerScaleMonitor+<GetMetricsAsync>d__1.MoveNext","level":2,"line":0},{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":3,"line":0},{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":4,"line":0},{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":5,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Extensions.Redis, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null","method":"Microsoft.Azure.WebJobs.Extensions.Redis.RedisPollingTriggerBaseScaleMonitor+<GetScaleResultAsync>d__21.MoveNext","level":6,"line":76,"fileName":"/home/vsts/work/1/s/src/Microsoft.Azure.WebJobs.Extensions.Redis/PollingTriggerBase/RedisPollingTriggerBaseScaleMonitor.cs"},{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":7,"line":0},{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":8,"line":0},{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":9,"line":0},{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter`1.GetResult","level":10,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Host, Version=3.0.39.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Azure.WebJobs.Host.Scale.ScaleManager+<GetTargetScalersResultAsync>d__12.MoveNext","level":11,"line":167,"fileName":"D:\\a\\_work\\1\\s\\src\\Microsoft.Azure.WebJobs.Host\\Scale\\ScaleManager.cs"}]

**Comment by mapalan** [comment]
Thanks for bringing this issue up. It should be fixed in #156
